FROM ubuntu
MAINTAINER Jeff Cole <coleti16@students.ecu.edu>


RUN apt-get -qq update
RUN apt-get install -y wget git build-essential cmake unzip curl
RUN apt-get install -qqy python3-setuptools python3-docutils python3-flask
